### ISSUE TITLE
occasional troika-text bug when spawning op from palette

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#131]
This doesn't always happen. Occurs when spawning an op from the palette using a controller. don't know how to reproduce this yet:

```shell
troika-three-text.esm.js:2725 Uncaught TypeError: Cannot create property '_input' on number '16711680'
    at Text._prepareForRender (troika-three-text.esm.js:2725:40)
    at Text.onBeforeRender (troika-three-text.esm.js:2537:14)
    at renderObject (three.module.js:28256:10)
    at renderObjects (three.module.js:28246:5)
    at renderScene (three.module.js:28170:40)
    at WebGLRenderer.render (three.module.js:27982:5)
    at eval (Loop.js:195:27)
    at onAnimationFrame (three.module.js:25935:36)
    at XRSession.onAnimationFrame (three.module.js:12999:3)
```

**Comment by michaelpalumbo** [comment]
haven't replicated in nearly a week. closing
