### ISSUE TITLE
Audio.js when receiving an empty document?

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#187]
when all ops have been removed from scene, the document being passed to Audio.js is ```{ }``` and this is causing the following error:

```shell
audio got new doc {}
TypeError: Cannot read property 'uuid' of undefined
    at doc2operations (D:\github\mischmasch\Components\Audio\Audio.js:68:16)    
    at Object.updateGraph (D:\github\mischmasch\Components\Audio\Audio.js:165:21)
    at Immediate.animate [as _onImmediate] (D:\github\mischmasch\app.js:2120:9) 
    at processImmediate (internal/timers.js:461:21)
```

**Comment by grrrwaaa** [comment]
It was failing probably because it was expecting to find a speaker. (I thought we had said that the speaker can't be removed from the scene.)

I have modified audio.js to handle the case of no speaker, so this doesn't error. It should play silence now.
