### ISSUE TITLE
deleting an op with multiple cables produces error, crashes app

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#206]
possibly related to #199 

had a patch with multiple connections. went to delete an op with 2 connections and this happened: 

```shell
D:\github\mischmasch\Components\Patch\Patch.js:266
            let destOp = this.document[destID].name
                                               ^

TypeError: Cannot read property 'name' of undefined
    at Patch.rebuild (D:\github\mischmasch\Components\Patch\Patch.js:266:48)
    at Immediate.animate (D:\github\mischmasch\app.js:2104:22)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by michaelpalumbo** [comment]
traced the error to a bug where connections are not being removed from src.output.connections objects. 

need something that, when given the uuid of the to-be-deleted op ```A```, searched all other op.outputs.connections for instances of ```A``` and deletes them
