### ISSUE TITLE
automerge now uses wasm, vite can't handle wasm without plugin

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#213]
error:

```shell
[vite] Internal server error: "ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other 
community plugins to handle this. Alternatively, you can use `.wasm?init` or `.wasm?url`. See https://vitejs.dev/guide/features.html#webassembly for more details.
      at Context.load (file:///D:/github/mischmasch/web/node_modules/vite/dist/node/chunks/dep-79892de8.js:41945:19)
      at Object.load (file:///D:/github/mischmasch/web/node_modules/vite/dist/node/chunks/dep-79892de8.js:43360:46)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async loadAndTransform (file:///D:/github/mischmasch/web/node_modules/vite/dist/node/chunks/dep-79892de8.js:41038:24)
      ```

**Comment by michaelpalumbo** [comment]
I do not yet know how to use the plugin that is suggested

**Comment by michaelpalumbo** [comment]
appears to be resolved. needed to upgrade node from v14 to v18

**Comment by michaelpalumbo** [comment]
update: reverted to webpack bc vite doesn't support wasm
