### ISSUE TITLE
notes from test study

### ISSUE THREAD

**Issue by michaelpalumbo** [worldmaking/mischmasch#258]
also grab notes from iphone notes app

//
high priority!

the following error occurs sometimes, and when it does it causes the whole app to crash. if webrtc can't connect, shouldn't cause a crash, should be handled and attempt to reconnect. we last multiple play sessions to this where players had nice patches going and then it crashed:

```shell

E:\GitHub\mischmasch\node_modules\wrtc\lib\index.js:49
  this._send(data);
       ^
DOMException [InvalidStateError]: RTCDataChannel.readyState is not 'open'
    at RTCDataChannel.send (E:\GitHub\mischmasch\node_modules\wrtc\lib\index.js:49:8)
    at E:\GitHub\mischmasch\Components\Patch\Patch.js:524:52
    at Array.forEach (<anonymous>)
    at Patch.updatePeers (E:\GitHub\mischmasch\Components\Patch\Patch.js:513:37)
    at Patch.update (E:\GitHub\mischmasch\Components\Patch\Patch.js:273:14)
    at Object.updateHandStateMachine (E:\GitHub\mischmasch\app.js:624:12)
    at Object.updateStateMachines (E:\GitHub\mischmasch\app.js:474:37)
    at Immediate.animate (E:\GitHub\mischmasch\app.js:2392:5)
    at process.processImmediate (node:internal/timers:476:21)

```

pc on the right made a large patch, it was sounding awesome, and then when i reconnected the other pc to the internet, it wiped the pc on the right's scene. 

//

need to record audio and video output of both PCs. but note that the pc on the right is not as optimized and drops frames and sometimes hangs outright even without OBS running. 

//

urgent: error when webrtc connection times out, this causes a crash of the app, when it should just be handled and retry the connection or go offline

//

urgent: scene not syncing when user joins after other player has started patching. only seems to share their state when both starting from a blank scene

//

they both said it was FUN

//

the PC on the right 'pacman' drops its framerate often. (it's louder too, you can hear it chugging up more often). 

// 

have them both start a little closer to the desks. 

// 

get a clamp and clamp the cable to the desk so that the plugs at the computer aren't being pulled on

// 

can we have the oculus running in the carpet area using an hdmi and usb extension so that both players have larger play area?

//

would be great to have feedback cables working...

//

what is the rate module? is it actually a source? doesn't appear to work that way...

// 

rename 'slide' op display name as 'low pass'

//

played in it for nearly 50 minutes straight

// 

said they enjoyed being surrounded by so many modules.

**Comment by michaelpalumbo** [comment]
make the jacks larger so that when patching many-to-one or many-to-many (if a cable is already in a jack and we want to spawn a new one). problem is that an existing cable makes it really hard to select the jack for spawning a new cable, instead the existing cable gets grabbed by mistake

**Comment by michaelpalumbo** [comment]
rename MIX to MIXER in the display text

**Comment by michaelpalumbo** [comment]
it would be cool to copy and paste a section of the patch.

**Comment by michaelpalumbo** [comment]
each issue here moved to issues #260 #261 #262 #263 #264 #265 #266 #267 respectively
